// Generated by CoffeeScript 1.8.0
(function() {
  var TodoApp, TodoList;

  TodoList = require('demo/list');

  TodoApp = React.createClass({
    displayName: 'TodoApp',
    getInitialState: function() {
      return {
        items: [],
        text: ''
      };
    },
    onChange: function(e) {
      return this.setState({
        text: e.target.value
      });
    },
    handleSubmit: function(e) {
      var nextItems, nextText;
      e.preventDefault();
      nextItems = this.state.items.concat([this.state.text]);
      nextText = '';
      return this.setState({
        items: nextItems,
        text: nextText
      });
    },
    render: function() {
      return React.createElement(React.DOM.div, null, React.createElement(React.DOM.div, null));
    }
  });

  React.render(React.createElement(TodoApp, null), $('#demo')[0]);

}).call(this);
